# Generated by Django 2.1.7 on 2019-04-25 21:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentData',
            fields=[
                ('GUID', models.UUIDField(blank=True, default=uuid.UUID('6a5e5d41-1078-45a8-8701-05e57ab51394'), editable=False, primary_key=True, serialize=False)),
                ('open', models.IntegerField(blank=True, null=True)),
                ('high', models.IntegerField(blank=True, null=True)),
                ('low', models.IntegerField(blank=True, null=True)),
                ('close', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('GUID', models.UUIDField(blank=True, default=uuid.UUID('5c7b461d-4bd8-4eea-b350-01bb6ae23d65'), editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('open', models.IntegerField(blank=True, null=True)),
                ('high', models.IntegerField(blank=True, null=True)),
                ('low', models.IntegerField(blank=True, null=True)),
                ('close', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('GUID', models.UUIDField(blank=True, default=uuid.UUID('fcd98ccd-92e5-4abc-82d2-930e3f191239'), editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('shares_outstanding', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Stocks'),
        ),
        migrations.AddField(
            model_name='currentdata',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.Stocks'),
        ),
    ]
