# Generated by Django 2.2 on 2019-05-01 10:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('GUID', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('shares_outstanding', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('GUID', models.UUIDField(blank=True, default=uuid.UUID('895e4293-a012-43f0-b8ff-5525bc65109d'), editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('open', models.IntegerField(blank=True, null=True)),
                ('high', models.IntegerField(blank=True, null=True)),
                ('low', models.IntegerField(blank=True, null=True)),
                ('close', models.IntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Stocks')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(null=True)),
                ('percent_change', models.IntegerField(null=True)),
                ('open', models.IntegerField(null=True)),
                ('high', models.IntegerField(null=True)),
                ('low', models.IntegerField(null=True)),
                ('current', models.IntegerField(null=True)),
                ('previous', models.IntegerField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('value', models.IntegerField(null=True)),
                ('trades', models.IntegerField(null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Stocks', unique=True)),
            ],
        ),
    ]
