# Generated by Django 2.1.7 on 2019-04-25 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentdata',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.UUID('9dd95a4d-a99c-4648-ad83-32344c199445'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.UUID('97bb6b1d-2100-42ce-90be-6dd7dff20acc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
