# Generated by Django 2.2 on 2019-05-01 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.UUID('07a10807-ba05-4865-a643-8ab23abf994d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
