# Generated by Django 2.2 on 2019-04-30 22:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190425_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentdata',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.UUID('b763fdf1-8a74-40e7-928b-4f8eb1abc15f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.UUID('e4807075-0c16-4baa-8002-edce0e5256c9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
