# Generated by Django 2.2 on 2019-05-01 10:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190501_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Stocks'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.UUID('08a552c8-a6e7-426c-8db2-ad141e157ae7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
