# Generated by Django 2.2 on 2019-05-01 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190501_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentdata',
            name='change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='current',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='open',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='percent_change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currentdata',
            name='previous',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.UUID('2278e82a-020d-447f-a8f3-23e6a8e15a2a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
