# Generated by Django 2.2 on 2019-05-01 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190501_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.UUID('50c260d7-3054-4375-b6cd-448f252a02f6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
