# Generated by Django 2.2 on 2019-05-01 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20190501_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldata',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.UUID('a122f217-df43-4dfe-95ff-ee1992b858f6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
