# Generated by Django 2.2 on 2019-05-01 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20190501_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.UUID('6176893c-1854-40fe-a1fb-e6f734218042'), editable=False, primary_key=True, serialize=False),
        ),
    ]
