# Generated by Django 2.2 on 2019-05-01 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20190501_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.UUID('cd956232-b276-4bd1-ab8b-f5a8db2e9a35'), editable=False, primary_key=True, serialize=False),
        ),
    ]
