# Generated by Django 2.2 on 2019-05-01 14:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20190501_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentdata',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Stocks'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.UUID('63262c67-98a6-4c95-beef-0e5de74d272c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
