# Generated by Django 2.2 on 2019-05-01 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20190501_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.UUID('c2f7d794-f7b8-4fe2-a32c-8d510bfa888a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
