# Generated by Django 2.2 on 2019-05-01 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20190501_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='GUID',
            field=models.UUIDField(blank=True, default=uuid.UUID('d4a5e8ca-160c-4fa3-b89d-a8b64ea2bb61'), editable=False, primary_key=True, serialize=False),
        ),
    ]
