# Generated by Django 2.2 on 2019-05-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20190501_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='historicaldata',
            unique_together={('stock', 'date')},
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='GUID',
        ),
    ]
