# Generated by Django 2.2 on 2019-05-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20190501_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
