# Generated by Django 2.2 on 2019-05-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20190502_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
