# Generated by Django 2.2 on 2019-05-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20190502_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='date',
            field=models.DateField(),
        ),
    ]
