# Generated by Django 2.1.7 on 2019-03-23 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GUID', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('tickers', models.CharField(max_length=30)),
            ],
        ),
    ]
