# Generated by Django 2.1.7 on 2019-03-23 20:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GUID', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('open', models.TextField()),
                ('high', models.TextField()),
                ('low', models.TextField()),
                ('close', models.TextField()),
                ('volume', models.TextField()),
                ('value', models.TextField()),
                ('dates', models.TextField()),
                ('ticker_GUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tickers')),
            ],
        ),
    ]
