# Generated by Django 2.1.7 on 2019-03-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stockdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='tickers',
            field=models.CharField(default='Placeholder', max_length=30),
        ),
    ]
