# Generated by Django 2.1.7 on 2019-03-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stockdata_tickers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'ordering': ('tickers',)},
        ),
        migrations.AlterModelOptions(
            name='tickers',
            options={'ordering': ('tickers',)},
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='ticker_GUID',
            field=models.CharField(max_length=100),
        ),
    ]
