# Generated by Django 2.2 on 2019-04-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190323_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockData',
        ),
        migrations.DeleteModel(
            name='Tickers',
        ),
    ]
